services:
    librinfo_seedbatch.admin.organism:
        class: Librinfo\SeedBatchBundle\Admin\OrganismAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoSeedBatchBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoSeedBatchBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    librinfo_seedbatch.admin.seed_producer:
        class: Librinfo\SeedBatchBundle\Admin\SeedProducerAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoSeedBatchBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [setManager, [@doctrine.orm.entity_manager]]
            - [ setTemplate, [edit, LibrinfoSeedBatchBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    librinfo_seedbatch.admin.seedfarm:
        class: Librinfo\SeedBatchBundle\Admin\SeedFarmAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedFarm, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seed_form_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.seedbatch:
        class: Librinfo\SeedBatchBundle\Admin\SeedBatchAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedBatch, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seed_batch_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.seedbatch_embedded:
        class: Librinfo\SeedBatchBundle\Admin\SeedBatchEmbeddedAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\SeedBatch, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.seedbatch_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.plot:
        class: Librinfo\SeedBatchBundle\Admin\PlotAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\Plot, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.plot_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seedbatch.admin.plot_embedded:
        class: Librinfo\SeedBatchBundle\Admin\PlotEmbeddedAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\Plot, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Seed Batches
                label: librinfo.seedbatch.plot_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_seed_batch.admin.certification:
        class: Librinfo\SeedBatchBundle\Admin\CertificationAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\Certification, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: Certification
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, BlastCoreBundle:CRUD:base_edit.html.twig ] ]
            - [ setTemplate, [ list, BlastCoreBundle:CRUD:base_list.html.twig ] ]
            - [ setTemplate, [ show, BlastCoreBundle:CRUD:base_show.html.twig ] ]

    librinfo_seed_batch.admin.certification_type:
        class: Librinfo\SeedBatchBundle\Admin\CertificationTypeAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\CertificationType, LibrinfoMediaBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: CertificationType
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoMediaBundle:CRUD:edit.html.twig ] ]
            - [ setTemplate, [ list, BlastCoreBundle:CRUD:base_list.html.twig ] ]
            - [ setTemplate, [ show, BlastCoreBundle:CRUD:base_show.html.twig ] ]

    librinfo_seed_batch.admin.certifying_body:
        class: Librinfo\SeedBatchBundle\Admin\CertifyingBodyAdmin
        arguments: [~, Librinfo\SeedBatchBundle\Entity\CertifyingBody, LibrinfoMediaBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.seedbatch.certifying_body_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoMediaBundle:CRUD:edit.html.twig ] ]
            - [ setTemplate, [ list, BlastCoreBundle:CRUD:base_list.html.twig ] ]
            - [ setTemplate, [ show, BlastCoreBundle:CRUD:base_show.html.twig ] ]

